/*
 * This file is generated by jOOQ.
 */
package ada.points.eventing.jooq.domain.tables;


import ada.points.eventing.jooq.domain.Indexes;
import ada.points.eventing.jooq.domain.Keys;
import ada.points.eventing.jooq.domain.Test;
import ada.points.eventing.jooq.domain.tables.records.EventsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Events extends TableImpl<EventsRecord> {

    private static final long serialVersionUID = 1003190410;

    /**
     * The reference instance of <code>test.EVENTS</code>
     */
    public static final Events EVENTS = new Events();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventsRecord> getRecordType() {
        return EventsRecord.class;
    }

    /**
     * The column <code>test.EVENTS.ID</code>.
     */
    public final TableField<EventsRecord, Integer> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.EVENTS.EVENT_TYPE_ID</code>.
     */
    public final TableField<EventsRecord, Integer> EVENT_TYPE_ID = createField(DSL.name("EVENT_TYPE_ID"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>test.EVENTS.CID</code>.
     */
    public final TableField<EventsRecord, String> CID = createField(DSL.name("CID"), org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>test.EVENTS.UUID</code>.
     */
    public final TableField<EventsRecord, String> UUID = createField(DSL.name("UUID"), org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>test.EVENTS.PAYLOAD</code>.
     */
    public final TableField<EventsRecord, String> PAYLOAD = createField(DSL.name("PAYLOAD"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>test.EVENTS.ADDED_AT</code>.
     */
    public final TableField<EventsRecord, Timestamp> ADDED_AT = createField(DSL.name("ADDED_AT"), org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>test.EVENTS</code> table reference
     */
    public Events() {
        this(DSL.name("EVENTS"), null);
    }

    /**
     * Create an aliased <code>test.EVENTS</code> table reference
     */
    public Events(String alias) {
        this(DSL.name(alias), EVENTS);
    }

    /**
     * Create an aliased <code>test.EVENTS</code> table reference
     */
    public Events(Name alias) {
        this(alias, EVENTS);
    }

    private Events(Name alias, Table<EventsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Events(Name alias, Table<EventsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Events(Table<O> child, ForeignKey<O, EventsRecord> key) {
        super(child, key, EVENTS);
    }

    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EVENTS_EVENT_TYPE_ID, Indexes.EVENTS_PRIMARY);
    }

    @Override
    public Identity<EventsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EVENTS;
    }

    @Override
    public UniqueKey<EventsRecord> getPrimaryKey() {
        return Keys.KEY_EVENTS_PRIMARY;
    }

    @Override
    public List<UniqueKey<EventsRecord>> getKeys() {
        return Arrays.<UniqueKey<EventsRecord>>asList(Keys.KEY_EVENTS_PRIMARY);
    }

    @Override
    public List<ForeignKey<EventsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<EventsRecord, ?>>asList(Keys.EVENTS_IBFK_1);
    }

    public EventTypes eventTypes() {
        return new EventTypes(this, Keys.EVENTS_IBFK_1);
    }

    @Override
    public Events as(String alias) {
        return new Events(DSL.name(alias), this);
    }

    @Override
    public Events as(Name alias) {
        return new Events(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(String name) {
        return new Events(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Events rename(Name name) {
        return new Events(name, null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }
}
