/*
 * This file is generated by jOOQ.
 */
package ada.points.eventing.jooq.domain;


import ada.points.eventing.jooq.domain.tables.EventTypes;
import ada.points.eventing.jooq.domain.tables.Events;
import ada.points.eventing.jooq.domain.tables.records.EventTypesRecord;
import ada.points.eventing.jooq.domain.tables.records.EventsRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<EventsRecord, Integer> IDENTITY_EVENTS = Identities0.IDENTITY_EVENTS;
    public static final Identity<EventTypesRecord, Integer> IDENTITY_EVENT_TYPES = Identities0.IDENTITY_EVENT_TYPES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<EventsRecord> KEY_EVENTS_PRIMARY = UniqueKeys0.KEY_EVENTS_PRIMARY;
    public static final UniqueKey<EventTypesRecord> KEY_EVENT_TYPES_PRIMARY = UniqueKeys0.KEY_EVENT_TYPES_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EventsRecord, EventTypesRecord> EVENTS_IBFK_1 = ForeignKeys0.EVENTS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<EventsRecord, Integer> IDENTITY_EVENTS = Internal.createIdentity(Events.EVENTS, Events.EVENTS.ID);
        public static Identity<EventTypesRecord, Integer> IDENTITY_EVENT_TYPES = Internal.createIdentity(EventTypes.EVENT_TYPES, EventTypes.EVENT_TYPES.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<EventsRecord> KEY_EVENTS_PRIMARY = Internal.createUniqueKey(Events.EVENTS, "KEY_EVENTS_PRIMARY", Events.EVENTS.ID);
        public static final UniqueKey<EventTypesRecord> KEY_EVENT_TYPES_PRIMARY = Internal.createUniqueKey(EventTypes.EVENT_TYPES, "KEY_EVENT_TYPES_PRIMARY", EventTypes.EVENT_TYPES.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<EventsRecord, EventTypesRecord> EVENTS_IBFK_1 = Internal.createForeignKey(ada.points.eventing.jooq.domain.Keys.KEY_EVENT_TYPES_PRIMARY, Events.EVENTS, "events_ibfk_1", Events.EVENTS.EVENT_TYPE_ID);
    }
}
