/*
 * This file is generated by jOOQ.
 */
package ada.points.eventing.jooq.domain;


import ada.points.eventing.jooq.domain.tables.EventTypes;
import ada.points.eventing.jooq.domain.tables.Events;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 795902002;

    /**
     * The reference instance of <code>test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>test.EVENTS</code>.
     */
    public final Events EVENTS = ada.points.eventing.jooq.domain.tables.Events.EVENTS;

    /**
     * The table <code>test.EVENT_TYPES</code>.
     */
    public final EventTypes EVENT_TYPES = ada.points.eventing.jooq.domain.tables.EventTypes.EVENT_TYPES;

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Events.EVENTS,
            EventTypes.EVENT_TYPES);
    }
}
